DROP TABLE if exists AUTO_TEST_ALMCOA_TRd;CREATE TABLE  AUTO_TEST_ALMCOA_TR (CALIBER_CODE VARCHAR(100),CALIBER_NAME VARCHAR(1000),CALIBER_SUBLEVEL VARCHAR(100),PARENT_CALIBER_CODE VARCHAR(100),
SEQ VARCHAR(100),DISPLAY_ORDER VARCHAR(100),HOLIDAY_ADJST_TP VARCHAR(100),
HOLIDAY_CDAR_CD VARCHAR(100),PRICING_CURVE_CODE VARCHAR(100),DISCOUNT_CURVE_CODE 
VARCHAR(100),CMPD_INTST_TP VARCHAR(100),SBJT_TP VARCHAR(100),INSTRUMENT_TP_CD 
VARCHAR(100),PMT_TP VARCHAR(100),INTST_PMT_FREQ VARCHAR(100),
INTST_PMT_FREQ_MULT VARCHAR(100),ACRU_INTST_BAS VARCHAR(100),DT_COUNTER_TP 
VARCHAR(100),RPRIC_FREQ VARCHAR(100),RPRIC_FREQ_MULT VARCHAR(100))